### ISSUE TITLE
Fails to build on 32-bit targets

### ISSUE THREAD

**Issue by rossburton** [nfs-ganesha/nfs-ganesha#371]
```
nfs-ganesha-2.7.0/src/SAL/nfs4_recovery.c:433:31: error: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'clientid4' {aka 'long long unsigned int'} [-Werror=format=]
  LogDebug(COMPONENT_CLIENTID, "chk for %lu",
                               ^~~~~~~~~~~~~
    clientid->cid_clientid);
    ~~~~~~~~~~~~~~~~~~~~~~      
nfs-ganesha-2.7.0/src/include/log.h:300:19: note: in definition of macro 'LogDebug'
        NIV_DEBUG, format, ## args); \
                   ^~~~~~
```

**Comment by dang** [comment]
This needs a PRIu64 rather than lu.  I don't suppose you could submit a patch?

**Comment by ffilz** [comment]
Let's fix this one.

**Comment by philproctor** [comment]
I have it fixed against tag V3.3 over in my repo here: https://github.com/homelab-library/glusterfs/tree/a7ff29945e9b231770adfb86dcaf9f993f7b5f8d/patches

Had to get these 32bit errors fixed to build for armv7

**Comment by ffilz** [comment]
Do the same problems exist in the upstream code in the next branch? If not, we can identify the patch that fixed them (it's quite possible they have been fixed in next) and mark it for backport.

If they aren't fixed, we need an upstream patch first that we can then backport to V3-stable. The patch submission process is here:  https://github.com/nfs-ganesha/nfs-ganesha/wiki/DevPolicy#Patch_Submission_Guidelines

**Comment by philproctor** [comment]
Confirmed at least some of the issues still exist in the `next` branch. Looks like the rados patch from here: https://github.com/homelab-library/glusterfs/tree/master/patches is needed and the `export.c` fix is needed. I don't have time to investigate at this moment what would be needed after that, but I had earlier confirmed that set of patches works on all versions from 2.8.3 to 3.3

**Comment by ffilz** [comment]
Considering how old this is, and there is another issue also with a patch which I applied as https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/512235 I'm going to close this one. Please open a new issue if either Ganesha V3.5 or V4 (next branch) doesn't compile. We can either slate patches for back port to V3.x and/or address any remaining issues in next.
