### ISSUE TITLE
showmount -e reverses ip octets if they are specified as CIDR

### ISSUE THREAD

**Issue by do11** [nfs-ganesha/nfs-ganesha#98]
Part of `/etc/ganesha/ganesha.conf`:

```
EXPORT
{
        Export_Id = 9;
        Path = "/space/common";
        Pseudo = "/common";
        FSAL {
                Name = XFS;
        }
        CLIENT
        {
                Clients = 192.168.33.56/29;
                Access_Type = RW;
        }
}
```

`showmount -e` output:

```
root@test:~# showmount -e stor
Export list for stor:
/space/common 56.33.168.192
```

But access checks are performed correctly. 192.168.33.60 box **can** RW access this export, and 56.33.168.192 **can't**.

This is nfs-ganesha from Centos 7:

```
root@stor:/etc/ganesha# rpm -qi nfs-ganesha
Name        : nfs-ganesha
Version     : 2.3.1
Release     : 4.el7
Architecture: x86_64
Install Date: Mon 02 May 2016 05:15:05 PM MSK
Group       : Applications/System
Size        : 1631827
License     : LGPLv3+
Signature   : RSA/SHA256, Thu 07 Apr 2016 12:52:34 PM MSK, Key ID 6a2faea2352c64e5
Source RPM  : nfs-ganesha-2.3.1-4.el7.src.rpm
Build Date  : Wed 06 Apr 2016 01:46:58 PM MSK
Build Host  : buildvm-07.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/nfs-ganesha/nfs-ganesha/wiki
Summary     : NFS Server running in user space
Description :
nfs-ganesha : NFS-GANESHA is a NFS Server running in user space.
It comes with various back-end modules (called FSALs) provided as
shared objects to support different file systems and name-spaces.
```

**Comment by malahal** [comment]
This may have been fixed by commit 2b5d4f81beb87bedafdacd86cb23a163cd27d01d, please try it out.

**Comment by malahal** [comment]
Just an FYI:
$ git tag --contains 2b5d4f81beb87bedafdacd86cb23a163cd27d01d 
V2.4.0.1
V2.4.0.2
V2.4.0.3
V2.4.0.4
V2.4.1
V2.5-dev-1
V2.5-dev-2
V2.5-dev-3
V2.5-dev-4
V2.5-dev-5
V2.5-dev-6
V2.5-dev-6a
V2.5-dev-6b
V2.5-dev-7

**Comment by srirampatil** [comment]
I tried this fix by back porting the commit to 2.3. With this fix the showmount output shows the correct IP address but the second part in CIDR is still missing.

For example, 192.168.33.56/29 is displayed in showmount output as 192.168.33.56.

**Comment by dang** [comment]
I don't see anything in that code that would print a masklen on 2.5.

**Comment by ffilz** [comment]
What is the status here?

**Comment by malahal** [comment]
The reverse string is fixed but the mask is not printed. We can either
raise a new issue ticket or change the subject of this ticket.

**Comment by ffilz** [comment]
Let's have a new issue
