### ISSUE TITLE
open_by_handle_at failes from client (virtiofsd)

### ISSUE THREAD

**Issue by aep** [nfs-ganesha/nfs-ganesha#980]
i'm exporting zfs over ganesha to virtiofsd into vms

the vm cannot write to an open file that was unliked

```
fd = open("file")
unlink("file")
write(fd) 
```

the underlying reason is that open_by_handle_at on the nfs client  returns `Stale file handle`

this is reproducable with:

```
dd if=/dev/zero of=/tmp/test bs=1M count=10
mkfs.ext4  /tmp/test
mount /tmp/test /mnt/src

cat  /etc/ganesha/ganesha.conf
EXPORT
{
	Export_Id = 3;
	Path = /mnt/src;
	Pseudo = /mnt/src;
	Access_Type = RW;
	Squash = noidsquash;
	FSAL {
		Name = VFS;
	}
}
```

compiling the examples from https://man7.org/linux/man-pages/man2/open_by_handle_at.2.html

then

```
./main1 main1  | ./main2
main2: open_by_handle_at: Stale file handle
```

debug log from ganesha:

```
28/07/2023 18:34:53 : epoch 64c3ee05 : ganesha.nfsd-792082[svc_2] vfs_check_handle :FSAL :INFO :Could not map fsid=0x3e46b7010fab1837.0x000000000000589b to filesystem

```

**Comment by aep** [comment]
attached is a complete repro in vagrant

[badnfs.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/12206659/badnfs.zip)

```
unzip badnfs.zip
cd badnfs
vagrant up
    default: main2: open_by_handle_at: Stale file handle

```

So this is a fresh debian vm, no zfs in the kernel (which i suspected might cause this as a side effect).
i'm confused why this is only broken for me when it's reproducible very reliably on any kernel.
same repro als works with fedora and archlinux.

**Comment by rohitrs1983** [comment]
@aep the bug is in your test code, main2.c
the input buffer to main2 is greater than 100 chars. so the input is truncated and part of the input data is lost.
please update #define LINE_SIZE 100
please change to #define LINE_SIZE 200 and test.

**Comment by aep** [comment]
thanks, that fixed it *facepalm*

i already discovered the test must be broken because virtiofsd is actually failing in name_to_handle_at, but this fails in open_by_handle_at, so it isnt a good repro.

instead i'm now suspecting it isnt ganesha at all but the kernel nfs client.

https://gitlab.com/virtio-fs/virtiofsd/-/issues/116#note_1492765291


specifically name_to_handle_at is only failing when the mount is inside a namespace.
do we have a good userspace client to double check this theory?

**Comment by aep** [comment]
https://github.com/sahlberg/fuse-nfs   does NOT have this issue. so this is a kernel bug?

(never mind, that just doesnt implement the api so i idk what even happens)

**Comment by ffilz** [comment]
I'm not clear what all is going on. I don't see a mount command from client to Ganesha.

It also seems that perhaps the issue has been resolved?

**Comment by aep** [comment]
the issue persists, but i do believe its a bug in the kernel client, not ganesha.
i understand you cant help with that

**Comment by ffilz** [comment]
OK, closing as external to Ganesha
